# Exported from Render on 2024-07-17T08:27:41Z
services:
- type: web
  name: alpha-blog-kaif
  runtime: docker
  repo: https://github.com/mkaif404/alpha-blog
  plan: free
  envVars:
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeploy: false
version: "1"
