# render.yaml
services:
  - type: web
    name: my-rails-app
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rake assets:precompile db:migrate
    startCommand: bundle exec rails server -b 0.0.0.0 -p 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my-rails-db
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        sync: false # Do not sync this value from your local environment
databases:
  - name: my-rails-db
    engine: postgresql
    plan: free